### ISSUE TITLE
could you provide your data?

### ISSUE THREAD

**Issue by chamecall** [cuongphamduc/CNNLSTM#2]
Hello guys. Thanks for your work.
In your paper you mentioned that you did your training data publicly available but there are no any links neither in paper nor in here to the dataset.
So I'm wondering if you could provide an access to the data to train your model.

**Comment by cuongphamduc** [comment]
Hi, this is the dataset that we use : https://mivia.unisa.it/datasets/video-analysis-datasets/fire-detection-dataset/ .
